feeds/urls.py
from django.urls import path
from . import views

app_name = 'feeds'

urlpatterns = [
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('fetch/', views.get_feeds, name='fetch')
]

the_reader/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('', include('feeds.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

feeds/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.text import slugify

# Create your models here.
User = get_user_model()


class Category(LoginRequiredMixin, models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(editable=False, blank=True, default='')

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        self.slug = slugify(self.name)
        super().save(**kwargs)

    class Meta:
        ordering = ['name']


class FeedSource(LoginRequiredMixin, models.Model):
    name = models.CharField(max_length=256, unique=True)
    url = models.URLField(unique=True)
    description = models.TextField(blank=True, null=True, default='')
    user = models.ForeignKey(User, related_name='sources', blank=True, null=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, related_name='sources')

    def __str__(self):
        return self.name

    def get_articles(self):
        return self.articles.all().order_by('-published_at')[:8]

    class Meta:
        ordering = ['name']


class Feed(LoginRequiredMixin, models.Model):
    name = models.CharField(max_length=256, blank=True, default='')
    url = models.URLField(unique=True)
    feed_source = models.ForeignKey(FeedSource, related_name='feeds', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='feeds', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.category.name + '_' + self.feed_source.name
        super().save(*args, **kwargs)


class Article(models.Model):
    title = models.CharField(max_length=256)
    text = models.TextField()
    link = models.URLField(blank=True, null=True, default='')
    image_url = models.URLField(blank=True, null=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    published_at = models.DateTimeField()
    feed_source = models.ForeignKey(FeedSource, related_name='articles', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='articles', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['published_at']

feeds/views.py
from django.views.generic import DetailView
from django.http import HttpResponseRedirect

from .models import FeedSource, Category, Article

from datetime import datetime

import feedparser
from dateutil import parser


# Create your views here.

def get_feeds(req):
    for fs in FeedSource.objects.all():
        for feed in fs.feeds.all():
            rss_feed = feedparser.parse(feed.url)
            # Save articles
            for entry in rss_feed.entries:
                entry_date = parser.parse(entry.published)

                if not feed.last_updated or (entry_date >= feed.last_updated):
                    try:
                        article = Article(title=entry.title, link=entry.link, text=entry.summary,
                                          published_at=entry_date,
                                          image_url=entry.links[1]['href'],
                                          feed_source=fs,
                                          category=feed.category)
                        article.save()
                    except (AttributeError, IndexError) as error:
                        print(error)
                        pass

            feed.last_updated = datetime.now()
            feed.save()

    return HttpResponseRedirect('/')


class CategoryDetailView(DetailView):
    model = Category
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        category = self.get_object()
        context = super().get_context_data(**kwargs)
        feeds_sources = FeedSource.objects.filter(categories__name__contains=category.name)

        context['feeds_sources'] = feeds_sources
        context['title'] = category.name

        return context

the_reader/views.py
from django.views.generic import TemplateView
from feeds.models import FeedSource


# Views

class HomeView(TemplateView):
    template_name = 'index.html'

    title = 'Accueil'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        context['feed_sources'] = FeedSource.objects.all()

        return context

feeds/templates/feeds/category_detail.html
{% extends 'master.html' %}

{% block header %}

    <div class="row mt-5">
        <div class="col-12">
            <h4 class="heading text-center">
                {{ category.name }}
            </h4>
        </div>
    </div>

{% endblock %}

{% block content %}

    <div class="row">
        {% for fs in feeds_sources %}

            {% if fs.articles.count > 0 %}

                {% include 'feeds/partials/articles-block.html' with articles=fs.get_articles %}

            {% endif %}

        {% empty %}

            <div class="col-12">
                <h4 class="text-muted text-center my-5">
                    Il n'y a aucun article dans cette catégorie pour l'instant.
                </h4>
            </div>

        {% endfor %}
    </div>

{% endblock %}

feeds/templates/feeds/partials/articles-block.html
{% load strip_img_tag %}

<div class="box-section mb-4 col-12 col-md-4">
    <p class="mb-1 box-section__source-title">
        {{ fs.name }}
        <small class="box-section__source-link">
            (<a target="_blank" href="{{ fs.url }}">{{ fs.url }}</a>)
        </small>
    </p>
    <div>
        {% for article in articles %}
            <p class="box-section__article text-truncate mb-0 py-1 overflow-hidden"
               id="{{ article.pk }}">
                <a target="_blank" data-toggle="popover" class="link-unstyled box-section__link"
                   title="{{ article.title | escape | safe }}"
                   data-content="{{ article.text | truncatewords_html:50 | strip_img }}"
                   href="{{ article.link }}">
                     <span class="badge badge-primary pr-1">
                        {{ article.published_at | date:'d-m' }}
                     </span>
                    {{ article.title | safe | truncatewords:9 }}
                </a>
            </p>
        {% endfor %}
    </div>
</div>

templates/index.html
{% extends 'master.html' %}
{% load strip_img_tag %}


{% block header %}
    <div class="row mt-5">
        <div class="col-12">
            <h4 class="heading">
                Derniers articles sur The Reader
            </h4>
        </div>
    </div>
{% endblock %}

{% block content %}

    <div class="row">
        {% for fs in feed_sources %}

            {% if fs.articles.count > 0 %}

                {% include 'feeds/partials/articles-block.html' with articles=fs.get_articles %}

            {% endif %}

        {% endfor %}
    </div>
{% endblock %}

templates/master.html
<!doctype html>
{% load staticfiles %}
{% load bootstrap4 %}
{% load sass_tags %}
<html lang="fr">
<head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {% bootstrap_css %}
        {#    {% bootstrap_javascript jquery='slim' %}#}
        <link rel="stylesheet" href="{% sass_src 'css/app.scss' %}">
        <title>The Reader - {{ title | default:'Accueil' }}</title>
</head>
<body>

    <div class="container-fluid px-0">
        {% include 'partials/navbar.html' %}
    </div>

    <div class="container">
        {% block header %}

        {% endblock %}
        {% block content %}

        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>

</html>

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <a href="#" class="navbar-brand text-light text-uppercase text-teal font-weight-bolder">
        The Reader
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if request.path == '/' %} active {% endif %}">
                <a href="{% url 'index' %}" class="nav-link">
                    Accueil
                </a>
            </li>

            {% for category in categories %}
                <li class="nav-item {% if category.slug in request.path %} active {% endif %}">
                    <a href="{% url 'feeds:category_detail' slug=category.slug %}" class="nav-link">
                        {{ category.name }}
                    </a>
                </li>
            {% endfor %}

        </ul>

    </div>

</nav>